version: "3.8"
services:
  app:
#    image: ghcr.io/limetric/openrct2.org:v3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - "./config:/home/node/app/config"
#      - "./customViews:/home/node/app/views/custom"
    ports:
      - "5000:80"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: openrct2
      MYSQL_USER: openrct2
      MYSQL_PASSWORD: letmein  
    volumes:
#      - "./data:/var/lib/mysql"
      - "./mysql_init:/docker-entrypoint-initdb.d"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 3s
      timeout: 6s
      retries: 30
