version: "3.8"
services:
  app:
#    image: ghcr.io/limetric/openrct2.org:v3
    build:
      target: development # can be either 'development' or 'release'
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - "./config:/home/node/app/config"
      - "./src:/home/node/app/src" # development target only
      - "./frontend:/home/node/app/frontend" # development target only
      - "./views:/home/node/app/views" # development target only
#      - "./customViews:/home/node/app/views/custom" # optional
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: openrct2
      MYSQL_USER: openrct2
      MYSQL_PASSWORD: letmein  
    volumes:
#      - "./data:/var/lib/mysql"
      - "./mysql_init:/docker-entrypoint-initdb.d"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 3s
      timeout: 6s
      retries: 30

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 9090:80
    environment:
      - PMA_HOST=db
      - PMA_USER=openrct2
      - PMA_PASSWORD=letmein
