version: '3'
services:
  app:
#    image: ghcr.io/limetric/openrct2.org:v3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=16
    volumes:
      - './config:/home/node/app/config'
#      - './customViews:/home/node/app/views/custom'
    ports:
      - "5000:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
