version: '3'
services:
  app:
    image: ghcr.io/limetric/openrct2.org:v2
    volumes:
      - './config:/home/app/config'
    ports:
      - "5000:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
