name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: node version, npm ci, build, and test
        run: |
          node -v
          NODE_ENV=development npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
          NODE_ENV: production
          BABEL_ENV: production
